"$schema" = 'https://starship.rs/config-schema.json'

# Gruvbox color palette
palette = 'gruvbox_dark'

[palettes.gruvbox_dark]
fg = '#ebdbb2'
bg = '#282828'
red = '#fb4934'
green = '#b8bb26'
yellow = '#fabd2f'
blue = '#83a598'
purple = '#d3869b'
aqua = '#8ec07c'
orange = '#fe8019'

[character]
success_symbol = '[➜](green)'
error_symbol = '[✗](red)'

[directory]
style = 'blue'

[git_branch]
symbol = ''
style = 'purple'

[git_status]
style = 'yellow'
format = '([$all_status$ahead_behind]($style) )'

[cmd_duration]
min_time = 2000
format = '[$duration](orange) '

[aws]
disabled = true

